(letrec ((counter 0)
         (inc (lambda ()
                (letrec ((old counter)
                         (new (+ old 1)))
                  (if (cas counter old new)
                    #t
                    (inc)))))
         (dec (lambda ()
                (letrec ((old counter)
                         (new (- old 1)))
                  (if (cas counter old new)
                    #t
                    (dec)))))
         (t1 (spawn (inc)))
         (t2 (spawn (dec)))
         (t3 (spawn (dec))))
  (join t1)
  (join t2)
  counter)
