(letrec ((lock #f)
         (acquire (lambda ()
                    (if (cas lock #f #t)
                        nil
                        (acquire))))
         (release (lambda ()
                    (set! lock #f)))
         (counter 0)
         (inc (lambda ()
                (acquire)
                (set! counter (+ counter 1))
                (release)))
         (t1 (spawn (inc)))
         (t2 (spawn (inc))))
  (join t1)
  (join t2)
  counter)
