(letrec ((counter 0)
         (f (lambda ()
              (letrec ((old counter)
                       (new (+ old 1)))
                (if (cas counter old new)
                  "done"
                  (f)))))
         (t1 (spawn (f)))
         (jt1 (join t1))
         (t2 (spawn (f)))
         (jt2 (join t2))
         (t3 (spawn (f)))
         (jt3 (join t3))
         (t4 (spawn (f)))
         (jt4 (join t4))
         (t5 (spawn (f)))
         (jt5 (join t5)))
  counter)
